name: build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: deps
        run: "sudo apt-get update && sudo apt-get install just buildah"
      - name: "build"
        run: just build workdir=$PWD
      - name: "compress"
        run: "tar czvf image.system.tar.gz system.ociarchive"
      - name: "archive"
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: image.*.tar.gz
